### ISSUE TITLE
None of the links on the API webpages work

### ISSUE THREAD

**Issue by dbuscombe-usgs** [yotarazona/scikit-eo#14]
ping https://github.com/openjournals/joss-reviews/issues/6692

Every single 'SOURCE' link on the API pages of the website is broken (404 - Not found)

**Comment by yotarazona** [comment]
Could you please share the link is not working?. I took a look at all the links and everything is working.

**Comment by dbuscombe-usgs** [comment]
All of the 'SOURCE' links are broken

I just checked and they are all still down, e.g.

https://yotarazona.github.io/scikit-eo/scikeo/pca.py#L0

**Comment by yotarazona** [comment]
Hi @dbuscombe-usgs. Please find attached a gif where you can see all the links related to the package are working. 

![gif](https://github.com/yotarazona/scikit-eo/assets/143953867/b470b293-1435-47d3-9d38-4ac09dcb3f8d)

Maybe you have some old version of the website in your browser cache.
Best.

**Comment by dbuscombe-usgs** [comment]
![image](https://github.com/yotarazona/scikit-eo/assets/3596509/65a2ac9f-9ac8-48d7-970d-446d60decd10)

Thanks for the gif. I'm only talking about the SOURCE links on the API pages. It's not a big deal, but probably an easy fix. My cache is clear. This is a real bug.

**Comment by Nowosad** [comment]
Hi @dbuscombe-usgs -- I believe that you are using a wrong website. The correct one is https://yotarazona.github.io/scikit-eo/

**Comment by KBodolai** [comment]
I'm getting the same as @dbuscombe-usgs above. I think it's because the links it points to are something like:

`https://yotarazona.github.io/scikit-eo/scikeo/mla.py#L23`

where it should be:

`https://github.com/yotarazona/scikit-eo/blob/main/scikeo/mla.py#L23`

**Comment by yotarazona** [comment]
Hi @KBodolai, thanks for this unnoticed tip!. All links were updated now :).

**Comment by KBodolai** [comment]
have the docs been deployed? I'm still getting the same issues when I try to get to the source code.

**Comment by yotarazona** [comment]
Hi @KBodolai, sorry. It was fixed.

**Comment by KBodolai** [comment]
I can confirm, great to have this working :)
