### ISSUE TITLE
Potential issue with Example 02 and `confintervalML`

### ISSUE THREAD

**Issue by KBodolai** [yotarazona/scikit-eo#22]
In notebook 02 you compute the confidence interval for the area estimation as described in Olofsson 2014. 

There's a subtlety in these sample-based are estimation / accuracy estimation methods, which is that the sample needs to be a probability sample, which is not generally the case when you collect samples to train a machine learning model. 

As far as I understand, the confusion matrix here comes from something similar to what we do in example 01, and not an independent probability sample, in which case, the estimators proposed by Olofsson are not applicable.

If I'm wrong, I think it's probably worth documenting how this data should be generated and how to apply this function properly.

**Comment by yotarazona** [comment]
Thank you @KBodolai ! for this comment/suggestion. While the sampling design should be a probability sampling design, i.e. simple random, stratified random and systematic random; in practice, probability sampling is not complied with. From my experience, I have worked with a probability sampling design (stratified random and simple random), but at other times they are designs that follow other protocols as mentioned by Olofsson et al. (2014).

In particular, to be transparent with the use of this function I have added more details about this within the process module. In addition, you can also find clarifications on this topic in tutorial number [2](https://github.com/yotarazona/scikit-eo/blob/main/examples/notebooks/02.%20Estimated%20area%20and%20uncertainty%20in%20Machine%20Learning.ipynb).

**Comment by KBodolai** [comment]
Yes, my main concern here is that if the sampling design is not a probability sampling design (and not a stratified design in this particular case), the estimators implemented are not valid.

Great to have some more documentation around it in the module,  and clarification in the notebooks :)

(particularly as one of the intended use cases is to educate users!)
