### ISSUE TITLE
Version in init not automatically updated.

### ISSUE THREAD

**Issue by KBodolai** [yotarazona/scikit-eo#23]
The version in `__init__.py` is hardcoded to 0.1.0, whereas the latest release is 0.2.26. 

I suggest something like this can give the user the right version to check when they try to check the package version within the python session:

```python
"""Top-level package for scikit-eo."""

import importlib.metadata

__author__ = """Yonatan Tarazona Coronel"""
__email__ = 'geoyons@gmail.com'
__version__ = importlib.metadata.version('scikeo')
```

**Comment by yotarazona** [comment]
Hi @KBodolai. Thanks for that, Done!.
