### ISSUE TITLE
Notebooks don't run locally without modifcation. Guidance would be helpful

### ISSUE THREAD

**Issue by dbuscombe-usgs** [yotarazona/scikit-eo#7]
ping JOSS https://github.com/openjournals/joss-reviews/issues/6692

I am trying to run the provided notebooks from source, not on colab. I shouldn't need to run the examples on any third-party platform like colab. They should run locally

None of the notebooks in the examples folder run, because 

1. jupyter and google are not found and need to be installed separately. This would need to be communicated to the user, see https://github.com/yotarazona/scikit-eo/issues/5
2. the datasets are not accessible, for example "/content/drive/MyDrive/Packages/scikit-eo_data/01_machine_learning/LC08_232066_20190727_SR.tif" doesn't exist

**Comment by dbuscombe-usgs** [comment]
I was able to find the dataset for the first notebook, 'Machine Learning' on the webiste [here](https://yotarazona.github.io/scikit-eo/get-started/). Thanks for providing these data. I was able to comment out the google drive cells, update the paths to my locally downloaded data, and run the first notebook. 

Perhaps just some more clarification should be provided, namely
1. that it is possible to run the notebooks locally, with some modifications and by downloading the data locally
2. also providing a stable computational environment will all needed dependencies

**Comment by dbuscombe-usgs** [comment]
I note that you have done a good job at linking to datasets in other notebooks other than number 1. I think the only things required are
1. a link in the first notebook to the data
2. a higher-level description of how to run locally

**Comment by yotarazona** [comment]
Thank you so much @dbuscombe-usgs !. Done, each notebook has a correct link to download data files. A higher-level description of how to run data locally was added in the new version of the package.
