### ISSUE TITLE
Error in notebook 2. Unknown variable `n`

### ISSUE THREAD

**Issue by dbuscombe-usgs** [yotarazona/scikit-eo#8]
ping https://github.com/openjournals/joss-reviews/issues/6692

The following line
```result = confintervalML(matrix = values, image_pred = img, pixel_size = 30, nodata = -9999)```

returns the following error

```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
Cell In[18], line 1
----> 1 result = confintervalML(matrix = values, image_pred = img, pixel_size = 30, nodata = -9999)

File ~/miniconda3/envs/scikiteo/lib/python3.10/site-packages/scikeo/process.py:251, in confintervalML(matrix, image_pred, pixel_size, conf, nodata)
    248 # copy of matrix
    249 matConf = matrix.astype(float).copy()
--> 251 for i in range(n):
    252     matConf[i,:] = (matConf[i,:]/ni[i])*wi[i]
    254 # user's accuracy

UnboundLocalError: local variable 'n' referenced before assignment
```

this seems to be an error related to a variable, `n`, not being specified in the scikit-eo function `confintervalML`

**Comment by yotarazona** [comment]
Hi @dbuscombe-usgs, thanks for your feedback. This notebook was run but I didn't get any error related to the variable ```n```. I am using the v0.2.23. Tell me if this error still persists.

**Comment by yotarazona** [comment]
Did you make sure if this issue is still doesn´t work out?. @dbuscombe-usgs

**Comment by dbuscombe-usgs** [comment]
I'll review later today

**Comment by yotarazona** [comment]
Great! Thanks

**Comment by dbuscombe-usgs** [comment]
Look good. I can sign off on this now. Thanks for addressing all these comments!
