### ISSUE TITLE
Error in notebook 10_Logistic_regression_in_remote_sensing.ipynb

### ISSUE THREAD

**Issue by dbuscombe-usgs** [yotarazona/scikit-eo#9]
ping https://github.com/openjournals/joss-reviews/issues/6692

Heads-up that the link provided does not contain the data `Variables.tif`, which is what is required to run the example. Please update with the new link to the data

**Comment by yotarazona** [comment]
Hi @dbuscombe-usgs, thanks for your time and your review of the package. 
Done, all links were updated.
